[package]
name = "dao"
description = "A library for managing application state."
repository = "https://github.com/knutsoned/dao"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
